intents = [
    "SolicitarTurno_Mamografia_Imagenes_CentroAtencion",
    "ModificarTurno_Mamografia_Imagenes_CentroAtencion",
    "CancelarTurno_Mamografia_Imagenes_CentroAtencion",
    "ConsultarResultados_Analisis_Laboratorio_Paciente",
    "SolicitarReceta_Medicamentos_Farmacia_Paciente",
    "RealizarPago_Servicios_Medicos_CentroAtencion",
    "SolicitarTurno_Radiografia_Imagenes_CentroAtencion",
    "ModificarTurno_Radiografia_Imagenes_CentroAtencion",
    "CancelarTurno_Radiografia_Imagenes_CentroAtencion",
    "ConsultarHistorialClinico_Paciente",
    "SolicitarInforme_Medico_CentroAtencion",
    "EnviarMensaje_Especialista_Paciente",
    "SolicitarConsulta_Especialista_CentroAtencion",
    "ModificarConsulta_Especialista_CentroAtencion",
    "CancelarConsulta_Especialista_CentroAtencion",
    "ConsultarDisponibilidad_Especialista_CentroAtencion",
    "SolicitarSegundaOpinion_Especialista_Paciente",
    "EnviarReceta_Medicamentos_Farmacia_CentroAtencion",
    "RealizarCobro_Servicios_Medicos_CentroAtencion",
    "SolicitarAutorizacion_Servicios_Medicos_Paciente",
    "ConsultarCobertura_Seguro_Salud_Paciente",
    "SolicitarTurno_Ecografia_Imagenes_CentroAtencion",
    "ModificarTurno_Ecografia_Imagenes_CentroAtencion",
    "CancelarTurno_Ecografia_Imagenes_CentroAtencion",
    "ConsultarDisponibilidad_Medico_CentroAtencion",
    "SolicitarConsulta_Medico_CentroAtencion",
    "ModificarConsulta_Medico_CentroAtencion",
    "CancelarConsulta_Medico_CentroAtencion",
    "SolicitarInformacion_Servicios_Medicos_CentroAtencion",
    "EnviarRecordatorio_Cita_Paciente",
    "RegistrarIngreso_Paciente_CentroAtencion",
    "RegistrarEgreso_Paciente_CentroAtencion",
    "SolicitarPrueba_Diagnostica_CentroAtencion",
    "ModificarPrueba_Diagnostica_CentroAtencion",
    "CancelarPrueba_Diagnostica_CentroAtencion",
    "ConsultarInformacion_Medicamento_Paciente",
    "SolicitarInformacion_Especialista_CentroAtencion",
    "EnviarRecordatorio_Pago_Paciente",
    "ConsultarDisponibilidad_Medicamento_Farmacia",
    "SolicitarEntrega_Medicamento_Farmacia_Paciente",
    "ModificarEntrega_Medicamento_Farmacia_Paciente",
    "CancelarEntrega_Medicamento_Farmacia_Paciente",
    "RegistrarPago_Factura_Servicios_Medicos_Paciente",
    "ConsultarInformacion_Seguro_Salud_Paciente",
    "SolicitarAutorizacion_Procedimiento_CentroAtencion",
    "ModificarAutorizacion_Procedimiento_CentroAtencion",
    "CancelarAutorizacion_Procedimiento_CentroAtencion",
    "SolicitarInformacion_Servicio_Salud_CentroAtencion",
    "EnviarResultado_Prueba_Diagnostica_Paciente",
    "ConsultarInformacion_Especialista_CentroAtencion",
    "SolicitarInformacion_Medicamento_Farmacia_CentroAtencion",
    "ConsultarInformacion_Servicio_Salud_CentroAtencion",
    "SolicitarInformacion_Procedimiento_CentroAtencion",
    "ConsultarInformacion_Procedimiento_CentroAtencion",
    "SolicitarInformacion_Medicamento_Farmacia_Paciente",
    "ConsultarInformacion_Medicamento_Farmacia_Paciente",
    "SolicitarInformacion_Servicio_Salud_Paciente",
    "ConsultarInformacion_Servicio_Salud_Paciente",
    "SolicitarInformacion_Procedimiento_Paciente",
]


intents = [
    {
        "name": "SolicitarTurno_Mamografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "ModificarTurno_Mamografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "CancelarTurno_Mamografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "ConsultarResultados_Analisis_Laboratorio_Paciente",
        "description": "",
    },
    {
        "name": "SolicitarReceta_Medicamentos_Farmacia_Paciente",
        "description": "",
    },
    {
        "name": "RealizarPago_Servicios_Medicos_CentroAtencion",
        "description": "",
    },
    {
        "name": "SolicitarTurno_Radiografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "ModificarTurno_Radiografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "CancelarTurno_Radiografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {"name": "ConsultarHistorialClinico_Paciente", "description": ""},
    {"name": "SolicitarInforme_Medico_CentroAtencion", "description": ""},
    {"name": "EnviarMensaje_Especialista_Paciente", "description": ""},
    {
        "name": "SolicitarConsulta_Especialista_CentroAtencion",
        "description": "",
    },
    {
        "name": "ModificarConsulta_Especialista_CentroAtencion",
        "description": "",
    },
    {
        "name": "CancelarConsulta_Especialista_CentroAtencion",
        "description": "",
    },
    {
        "name": "ConsultarDisponibilidad_Especialista_CentroAtencion",
        "description": "",
    },
    {
        "name": "SolicitarSegundaOpinion_Especialista_Paciente",
        "description": "",
    },
    {
        "name": "EnviarReceta_Medicamentos_Farmacia_CentroAtencion",
        "description": "",
    },
    {
        "name": "RealizarCobro_Servicios_Medicos_CentroAtencion",
        "description": "",
    },
    {
        "name": "SolicitarAutorizacion_Servicios_Medicos_Paciente",
        "description": "",
    },
    {"name": "ConsultarCobertura_Seguro_Salud_Paciente", "description": ""},
    {
        "name": "SolicitarTurno_Ecografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "ModificarTurno_Ecografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "CancelarTurno_Ecografia_Imagenes_CentroAtencion",
        "description": "",
    },
    {
        "name": "ConsultarDisponibilidad_Medico_CentroAtencion",
        "description": "",
    },
    {"name": "SolicitarConsulta_Medico_CentroAtencion", "description": ""},
    {"name": "ModificarConsulta_Medico_CentroAtencion", "description": ""},
    {"name": "CancelarConsulta_Medico_CentroAtencion", "description": ""},
    {
        "name": "SolicitarInformacion_Servicios_Medicos_CentroAtencion",
        "description": "",
    },
    {"name": "EnviarRecordatorio_Cita_Paciente", "description": ""},
    {"name": "RegistrarIngreso_Paciente_CentroAtencion", "description": ""},
    {"name": "RegistrarEgreso_Paciente_CentroAtencion", "description": ""},
    {"name": "SolicitarPrueba_Diagnostica_CentroAtencion", "description": ""},
]
